### ISSUE TITLE
consider renaming

### ISSUE THREAD

**Issue by krz** [jrs95/nlmr#1]
Thanks for this package. I only find it a bit unfortunate to name it exactly like an existing package on CRAN. That sometimes disturbs my workflow.

**Comment by jrs95** [comment]
Apologies Christoph, the publication refers to this package under this name, so we will not be renaming the package. I can however create a package with an alternative name if needed? I will take more care in the future to make sure the names of the packages do not clash with existing CRAN packages.

FYI, we updated this package last week to fix some minor bugs, so you may want to re-install the package anyway.

**Comment by krz** [comment]
thanks for your reply, that is completely understandable.
