### ISSUE TITLE
nlmr_summ

### ISSUE THREAD

**Issue by Yvonnehuang1316** [jrs95/nlmr#2]
Dear author,

Thank you very much for providing us with this wonderful R package.  In one of the recent publication 'Body mass index and all cause mortality in HUNT and UK Biobank studies: linear and non-linear mendelian randomisation analyses', they mentioned they used nlmr_summ function, seems it is from your package. Please can I ask is it still not revealed yet or it is from other R packages? 

Best wishes,
Yvonne

**Comment by jrs95** [comment]
Hi Yvonne,

Apologies for the delayed response - I have recently moved jobs and my github account was still sending notifications to my old University of Bristol address.

Unfortunately, the function is not available in the package currently. Due to my career change, my new job is industry, I have not had time to implement this function. I will let you know if and when I implement this function. Stephen Burgess (his email address is on the BMJ paper) should be able to help in the interim.

Best wishes,

James

**Comment by Yvonnehuang1316** [comment]
Hi James,

Thank you very for your reply,  as you suggested, I'll contact Stephen for
further implications. But still thank you very much for developing such a
good package for us!

All the best for your new job!

Best wishes,
Yvonne

James Staley <notifications@github.com> 于2019年10月10日周四 上午11:42写道：

**Comment by jrs95** [comment]
Hi Yvonne,

No worries - I'm glad you have found it useful! :)

Best wishes,

James

**Comment by ghost** [comment]
> Hi James, Thank you very for your reply, as you suggested, I'll contact Stephen for further implications. But still thank you very much for developing such a good package for us! All the best for your new job! Best wishes, Yvonne James Staley <notifications@github.com> 于2019年10月10日周四 上午11:42写道：
> […](#)

Hi Yvonne,

I'm trying to use nlmr_summ() function as well. Have you get the function from Stephen Burgess? 

Thank you,
Mei

**Comment by jrs95** [comment]
Hi Mei,

Let me know if Steve gets back to you. If he does not, I will follow this up with him.

Best wishes,

James

**Comment by ghost** [comment]
> Hi Mei,
> 
> Let me know if Steve gets back to you. If he does not, I will follow this up with him.
> 
> Best wishes,
> 
> James

Hi James,

Thank you so much for your prompt reply. I just reached out Stephen so I'm still waiting for his reply. I'll let you know if he doesn't reply in a certain time. Thank you for your help. Merry Christmas.

Regards,
Mei

**Comment by ghost** [comment]
Hi James,

I'm wondering if you could follow up with Steve on the nlmr_summ() function as I haven't got feedback yet. Thank you so much.

Regards,
Mei

**Comment by jrs95** [comment]
Hi Mei,

I would give this a little more time as it is the holiday season.

I’m sure Steve will respond in early January.

Best wishes,

James

**Comment by amymariemason** [comment]
Hi, I'm currently writing up an R-package for nlmr_summ. Feel free to get in touch with me on am2609@medschl.cam.ac.uk if you want access to the work in progress/ an update on when it is done. 

Amy Mason

**Comment by amymariemason** [comment]
Current working version of nlmr_summ is here: https://github.com/amymariemason/SUMnlmr
Still very much in beta, please drop me a line on here or at am2609@medschl.cam.ac.uk if any problems found.
