### ISSUE TITLE
Error：Aesthetics must be either length 1 or the same as the data (10000)

### ISSUE THREAD

**Issue by yeduo2019** [jrs95/nlmr#4]
Code：fp=fracpoly_mr(y=y,x=x,g=g,covar=dat[,c(3:15)],family='binomial',q=100,d=2,ci="model_se",fig=T,ref=2.84)
Error: Aesthetics must be either length 1 or the same as the data (10000)
But if d=1, it works fine. Hence,what does this situation means? could you help me answer this question?

**Comment by jrs95** [comment]
Hi yeduo2019,

Sorry to hear that you are having an issue with the package. 

This issue clearly relates to the plot, would you be able to download the latest version of the package and run the code above with fig=F and send back the results and I will try my best to see what the issue is.

Best wishes,

James

**Comment by yeduo2019** [comment]
Hi James,
Thank you very much for your reply. I have run the code above with fig=F ，and the error is "glm.fit: fitted probabilities numerically 0 or 1 occurred". But with "q=50,d=2,fig=T" it works fine. 

Besides, I have a another question. When Cochran Q p-value is <0.05, is this 'nlmr' method reliable ?  and should ''random effect" model be applied ?  

Looking forward for your reply.

Warm wishes,

yeduo2019

**Comment by jrs95** [comment]
Hi yeduo2019,

Yes, it appears that the number of quantiles seems to have been the problem.

These non-linear approaches rely on the genetic association in each quantile of the IV free exposure to be the same, in this case in the controls as you are looking at a binary outcome. This assumption is tested in the heterogeneity tests. If the data does not satisfy the assumption then a non-linear association can be induced even if the underlying association is linear. However, I would only be concerned if the heterogeneity results have small p-values in bigger quantiles than you are using, e.g. 10 quantiles.

Hope that helps.

Best wishes,

James
